### ISSUE TITLE
“Illegal string offset 'content'” when using “reset settings“

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-simple-hooks#10]
If you click “reset settings” at Genesis → Simple Hooks, you'll see this warning in the logs:

~~~
[05-Mar-2017 16:27:47 UTC] PHP Warning:  
Illegal string offset 'content' in /wp/wptest/wp-content/plugins/
genesis-simple-hooks/genesis-simple-hooks.php on line 152
~~~

(Develop branch)

**Comment by nathanrice** [comment]
e16d1b2

**Comment by nickcernis** [comment]
Confirmed! Resetting settings:

- [x] Resets settings
- [x] Does not produce warning

Production ready.
