### ISSUE TITLE
Register activation hook never fires

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-simple-hooks#11]
I do not see the expected “you cannot run Simple Hooks without Genesis” message from the `activate()` function when activating Simple Hooks with Twenty Seventeen active.

We removed the warning in Genesis Connect for WooCommerce, which may be worth applying here too.

**Comment by nathanrice** [comment]
Yeah, the activation hook code is still in there, but it doesn't do anything currently. The code that does all the heavy lifting is hooked to a Genesis hook, so we're already not at risk of any errors, I think.

I'm thinking about just removing the activation hook and switching to an admin notice if Genesis isn't active, or if minimum version requirements aren't met.

**Comment by nathanrice** [comment]
Fixed. What say you, @nickcernis ?

**Comment by nickcernis** [comment]
Looks good! (Can't edit labels here, but production ready. 👍 )
