### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-simple-hooks#13]
(Develop branch.) Same as https://github.com/copyblogger/genesis-simple-sidebars/issues/20 (except German isn't available as a language for Simple Hooks; I used https://wordpress.org/plugins/loco-translate/ to edit language files to test). 

The same solution posted there works for me here.

**Comment by nathanrice** [comment]
c079b9f

**Comment by nickcernis** [comment]
The title is now translated for me, but other text is not. :-(

<img width="562" alt="genesis_-_simple_hooks_ _wp_test_ _wordpress" src="https://cloud.githubusercontent.com/assets/647669/23653394/4ed4e1ea-0324-11e7-9608-f90abfd84be3.png">

If I do either of the following then all strings are translated:

1. Making `plugin_textdomain` a global function outside the class and binding it to `plugins_loaded` before the main plugin object is instantiated, which is what we did in Genesis Author Pro: https://github.com/copyblogger/Genesis-Author-Pro/blob/master/plugin.php#L30.

Or:

2. Making `plugin_textdomain` a static function (means also swapping `$this->plugin_textdomain` for `genesis-simple-hooks`):

```
function genesis_simple_hooks_load_textdomain() {
     load_plugin_textdomain( 'genesis-simple-hooks', false, dirname( plugin_basename( __FILE__ ) ) . '/languages/' );
}
```

Then calling it statically outside the class before we setup the plugin object:

`add_action( 'plugins_loaded', array('Genesis_Simple_Hooks', 'load_plugin_textdomain' ) );`

Result in either case:

<img width="452" alt="genesis_-_simple_hooks__italiano__ _wp_test_ _wordpress" src="https://cloud.githubusercontent.com/assets/647669/23653441/7bd9b328-0324-11e7-8c33-9e236033f8d7.png">

Here are the dummy Italian mo/po files I'm using to test this (first three strings contain `[Italiano]`) in case they help: http://d.pr/f/dN1W+

**Comment by nathanrice** [comment]
4ec328a

**Comment by nickcernis** [comment]
Va tutto bene!
