### ISSUE TITLE
genesis_load_admin_js deprecated message

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-simple-hooks#16]
> Notice: genesis_load_admin_js is deprecated since version 2.5.0! Use genesis_scripts()->enqueue_and_localize_admin_scripts() instead. in /wp-includes/functions.php on line 3831

**Comment by nickcernis** [comment]
Sharing notes from https://wordpress.org/support/topic/genesis_load_admin_js-deprecated-in-genesis-2-6-beta/ that this needs to be updated both times its used:

> - admin.php at line 169
> - class-genesis-simple-hooks-admin.php at line 109

**Comment by nathanrice** [comment]
There is no admin.php file in the latest version of Simple Hooks.
