### ISSUE TITLE
Get in Home Notice: Trying to get property of non-object

### ISSUE THREAD

**Issue by artmaug** [copyblogger/genesis-simple-hooks#17]
Hello, i get in homepage of my project - using define( 'WP_DEBUG', true ); - the following message:

Notice: Trying to get property of non-object in E:\wamp\www\core\wp-content\plugins\genesis-simple-hooks\genesis-simple-hooks.php(186) : eval()'d code on line 10

Notice: Trying to get property of non-object in E:\wamp\www\core\wp-content\plugins\genesis-simple-hooks\genesis-simple-hooks.php(186) : eval()'d code on line 14

How i can fix this?

Thanks a lot by your support!

**Comment by nickcernis** [comment]
Hi, @artmaug!

The message suggests there are two errors in the custom PHP code added at Genesis → Simple Hooks.

The code would be on line 10 and 14 of one or more of your PHP snippets. It will contain an object operator that looks something like this: `$object->property`. The error message means that `$object` is some data type other than an object.

How you fix this depends on the custom code being used, but you'll need to look through your snippets and remove or correct the code to remove these notices.

**Comment by artmaug** [comment]
Wow, thank you by the quick response!

**Comment by nickcernis** [comment]
You're welcome!

I'm closing this as it doesn't look like a bug in the plugin so far, but feel free to contact our support team with a link to this issue and a code sample if you need further help:

https://my.studiopress.com/help/
