### ISSUE TITLE
Escaped <code> tags appear in hook descriptions

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-simple-hooks#8]
In the develop branch (6f7a85e), hook descriptions appear wrapped with code tags:

<img width="558" alt="genesis_-_simple_hooks_ _wp_test_ _wordpress" src="https://cloud.githubusercontent.com/assets/647669/23586797/fa91b72e-0194-11e7-9d87-0716859545ad.png">

In the master branch tags appear as expected:

<img width="529" alt="genesis_-_simple_hooks_ _wp_test_ _wordpress" src="https://cloud.githubusercontent.com/assets/647669/23586803/2e1be088-0195-11e7-84c1-8f465297c716.png">

The cause is `esc_html()` in `generate_form_markup_from_hooks()`: https://github.com/copyblogger/genesis-simple-hooks/blob/develop/includes/class-genesis-simple-hooks-admin.php#L477

**Comment by nathanrice** [comment]
00118cc

**Comment by nickcernis** [comment]
Looks good to me!

**Comment by dreamwhisper** [comment]
Ha @nickcernis! You found that you and I have label capability before I even had a chance to tell you :D

**Comment by nickcernis** [comment]
@dreamwhisper It's like Christmas!

![label-maker](https://cloud.githubusercontent.com/assets/647669/23670281/20bdede8-035f-11e7-874f-87249568c70a.gif)
