### ISSUE TITLE
Duplicated 'for' attribute in checkbox labels

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-simple-hooks#9]
Hooks with multiple 'Unhook' checkboxes have duplicated `for` attributes in the labels. Clicking other labels toggles the first checkbox instead of the one for the clicked label:

![duplicated-labels](https://cloud.githubusercontent.com/assets/647669/23588835/296b69f2-01bb-11e7-937c-bb86de72f877.gif)

Affects 'Unhook' checkboxes on `wp_head`, `wp_meta`, and `genesis_after_entry`. (Develop branch.)

**Comment by nathanrice** [comment]
0360730

**Comment by nickcernis** [comment]
Confirmed. Clicking labels now toggles the correct checkbox.
